### ISSUE TITLE
Stream profile binary data to cloud storage rather than load it fully in memory first 

### ISSUE THREAD

**Issue by gregtatum** [firefox-devtools/profiler-server#31]
In #25, the route to upload profiles fully loads it in into memory through the `Concatenator` class. It then computes the hash. This is a bit dangerous, as the server could run out of memory, and be open to DOS attacks.

## Solution 1 - Non-hash file names

This solution involves not computing the hash for the filename, some other scheme would be created for assigning unique names to the profiles.

## Solution 2 - Move the file after upload

This would create a 2 step process for the buckets.

* The file would be stream uploaded to a temporary location.
* After streaming the hash can be computed
* Copy the temp file to the final location
* Delete the temp file
* Report the final hash to the user.

This is a bit riskier since the "move" operation is non-atomic and could fail, plus there can be additional usage charges for the copy operations.

**Comment by julienw** [comment]
here is a proposal for solution 1: https://docs.google.com/document/d/1rWfq2N7ie_XzGELq217QIJrOF500_BwHJFoauPY2Ayg/edit
